version: '3.3'
services:
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
    restart: always
  proxy_pool:
    image: "moongu0514/proxy_pool:latest"
    container_name: proxy_pool
    restart: always
    ports:
      - "5010:5010"
    depends_on:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  web-handler:
    image: "moongu0514/ocrwebsite:latest"
    container_name: web-handler
    restart: always
    ports:
      - '8000:8000'
  sms_att:
    image: "moongu0514/sms-att:latest"
    container_name: sms_att
    restart: always
    volumes:
    - "./log/:/app/log/"
    depends_on:
      - proxy_pool
    command: /bin/bash -c "sleep 45 && python -u startup.py"
