version: '3.3'
services:
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
  proxy_pool:
    image: "moongu0514/proxy_pool:latest"
    container_name: proxy_pool
    ports:
      - "5010:5010"
    depends_on:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
#  web-handler:
#    image: "web-handler:latest"
#    container_name: web-handler
#    volumes:
#      - "./image/:/app/image/"
#    command: /bin/bash -c "sleep 1 && python manage.py runserver"
  sms_att:
#    image: "sms-att:latest"
    image: "moongu0514/sms-att:latest"
    container_name: sms_att
    volumes:
    - "./log/:/app/log/"
    depends_on:
      - proxy_pool
    command: /bin/bash -c "sleep 45 && python -u startup.py"
